name: "pretextsnapshot"
description:a module to generate images from Pretext contact maps.
keywords:
  - pretext
  - picture
tools:
  - "pretextsnapshot":
      description: "Commandline image generator for Pretext Hi-C genome contact maps."
      homepage: "https://github.com/wtsi-hpag/PretextSnapshot"
      documentation: "https://github.com/wtsi-hpag/PretextSnapshot"
      tool_dev_url: "https://github.com/wtsi-hpag/PretextSnapshot"
      licence: "['https://github.com/wtsi-hpag/PretextSnapshot/blob/master/LICENSE']"

input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]

  - pretext:
      type: file
      description: pretext hic map
      pattern: "*.pretext"

output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', single_end:false ]
  - versions:
      type: file
      description: File containing software versions
      pattern: "versions.yml"
  - picture:
      type: file
      description: PNG file
      pattern: "*.png"

authors:
  - "@epaule"
